export const GET_PERSONS_LOAD = "GET_PERSONS_LOAD";
export const GET_PERSONS_SUCCESS = "GET_PERSONS_SUCCESS";
export const GET_PERSONS_FAIL = "GET_PERSONS_FAIL";

export const DELETE_CONTACT = "DELETE_CONTACT";
export const GET_PERSON = "GET_PERSON";
